version: "2.3"

services:

  1_open-proxy:
    image: approov/astropik-proxy-nodejs:${ENVIRONMENT:-dev}
    build:
      context: ./docker/build
      dockerfile: nodejs.Dockerfile
    container_name: "astropik-open-proxy"
    hostname: "${ENVIRONMENT:-dev}.astropik"
    working_dir: /home/node/workspace/steps/proxy/node/1_open-proxy
    env_file:
      - ./.env
    volumes:
      - ./:/home/node/workspace
    command:
      - npm
      - start
    ports:
      - 127.0.0.1:${STEP_1_PROXY_PORT}:${STEP_1_PROXY_PORT}
    networks:
      - astropik
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=${ENVIRONMENT:-dev}.astropik"
      - "traefik.docker.network=traefik"
      - "traefik.port=${ASTROPIK_HTTP_PORT:? Missing ASTROPIK_HTTP_PORT}"
      - "traefik.frontend.rule=Host:${ASTROPIK_PUBLIC_DOMAIN:? Missing ASTROPIK_PUBLIC_DOMAIN}"
networks:
  astropik:
    driver: "bridge"
  traefik:
    external: true
